# Base image
FROM --platform=linux/arm64/v8 arm64v8/python:3.10-bullseye as build

RUN apt-get update && apt-get install -y build-essential curl
ENV VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"


COPY --from=ghcr.io/astral-sh/uv:0.5.14 /uv /uvx /bin/
COPY requirements.txt /usr/src/
WORKDIR /usr/src
RUN uv venv /opt/venv && \
    uv pip install --no-cache -r requirements.txt


# App image
FROM --platform=linux/arm64/v8 arm64v8/python:3.10-bullseye
COPY --from=build /opt/venv /opt/venv

# Activate the virtualenv in the container
# See here for more information:
# https://pythonspeed.com/articles/multi-stage-docker-python/
ENV PATH="/opt/venv/bin:$PATH"

COPY ./app /usr/src/app
WORKDIR /usr/src/app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/usr/src/app/", "--log-level", "debug" ]
